"""Orchestration: a config dict -> a kernel (or host) specialized to it.

generate_kernel pipeline:  select skeleton -> splice fragments -> resolve #if
(drop dead branches) -> substitute constexpr values -> assert no residual
directives.  The result is a kernel with no knob conditionals — only the taken
path, reading like hand-written code for that one combo."""

from __future__ import annotations

import re

from . import directives, fragments, spec, substitute

RUNTIME_PY = fragments.KERNELS_DIR / "_runtime.py"

# After resolution the rendered kernel must contain no preprocessor conditional
# directives (every one is resolved at generation).  `if constexpr` may still be
# present for knobs not yet converted to #if — that's fine, it just isn't
# specialized; this guard only catches a #if that failed to resolve.
_RESIDUAL_DIRECTIVE = re.compile(r"(?m)^\s*#\s*(if|elif|else|endif)\b")


def _strip_module_docstring(src: str) -> str:
    """Drop a leading triple-quoted module docstring, if present."""
    m = re.match(r'\s*(?:"""|\'\'\')', src)
    if not m:
        return src
    quote = src[m.end() - 3:m.end()]
    end = src.find(quote, m.end())
    if end == -1:
        return src
    return src[end + 3:].lstrip("\n")


def generate_kernel(config: dict) -> str:
    """Return the kernel.cu specialized to `config` (a dict of knob values +
    'skeleton')."""
    spec.validate(config)
    knobs = spec.int_knobs(config)
    src = (fragments.KERNELS_DIR / config["skeleton"] / "kernel.cu").read_text()
    src = fragments.splice(src)                              # inject shared building blocks
    src = directives.resolve(src, knobs)                     # drop dead #if branches
    src = substitute.substitute_kernel_constexprs(src, **knobs)   # set live constants
    if _RESIDUAL_DIRECTIVE.search(src):
        raise RuntimeError("codegen: unresolved #if directive remained after resolve()")
    return src


def generate_host(config: dict) -> str:
    """Return a *self-contained* host script (runtime preamble + tier launcher),
    specialized to `config` (needs 'skeleton' and 'label')."""
    spec.validate(config, need_label=True)
    knobs = spec.int_knobs(config)
    runtime = _strip_module_docstring(RUNTIME_PY.read_text())
    launcher = (fragments.KERNELS_DIR / config["skeleton"] / "launcher.py").read_text()
    launcher = substitute.substitute_launcher_constants(launcher, **knobs)
    header = (
        '"""Self-contained matmul kernel launcher generated by mmcomposer.\n'
        "\n"
        f"Tier: {config['label']}\n"
        f"Config: BM={config['BM']} BN={config['BN']} BK={config['BK']} "
        f"NS={config['NS']} GROUP_SIZE_M={config['GROUP_SIZE_M']} "
        f"NUM_WARPS={config['NUM_WARPS']} "
        f"PERSISTENT={config.get('PERSISTENT', 0)} "
        f"EPILOGUE_OVERLAP={config['EPILOGUE_OVERLAP']} "
        f"EPILOGUE_SPLIT={config['EPILOGUE_SPLIT']} "
        f"EPILOGUE_L1_NO_ALLOC={config['EPILOGUE_L1_NO_ALLOC']} "
        f"EPILOGUE_TMA_PIPELINED={config['EPILOGUE_TMA_PIPELINED']}\n"
        "\n"
        "Run with:  python <this file>.py   (kernel.cu must sit alongside it)\n"
        "Requires:  torch, numpy, cuda-python (cuda.bindings), and nvcc on PATH.\n"
        '"""\n'
    )
    return f"{header}\n{runtime}\n\n# ===== tier launcher =====\n\n{launcher}"
